version: 2

run:
  timeout: 5m
  go: "1.25"
  tests: true

linters:
  enable:
    - bodyclose
    - errcheck
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - gocritic
    - nakedret
    - gosec
    - prealloc

formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt

formatters-settings:
  goimports:
    local-prefixes: github.com/goodnatureofminers/blockinsight7000-backend

linters-settings:

  revive:
    severity: warning
    rules:
      - name: exported
      - name: var-naming
      - name: blank-imports
      - name: indent-error-flow
      - name: errorf
      - name: range-val-in-closure
      - name: early-return

  gocritic:
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - commentFormatting
      - paramTypeCombine

  nakedret:
    max-func-lines: 20

  gosec:
    excludes:
      - G104
      - G601

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
