// Code generated by MockGen. DO NOT EDIT.
// Source: types.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/goodnatureofminers/blockinsight7000-backend/internal/utxo/model"
)

// MockClickhouseRepository is a mock of ClickhouseRepository interface.
type MockClickhouseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClickhouseRepositoryMockRecorder
}

// MockClickhouseRepositoryMockRecorder is the mock recorder for MockClickhouseRepository.
type MockClickhouseRepositoryMockRecorder struct {
	mock *MockClickhouseRepository
}

// NewMockClickhouseRepository creates a new mock instance.
func NewMockClickhouseRepository(ctrl *gomock.Controller) *MockClickhouseRepository {
	mock := &MockClickhouseRepository{ctrl: ctrl}
	mock.recorder = &MockClickhouseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickhouseRepository) EXPECT() *MockClickhouseRepositoryMockRecorder {
	return m.recorder
}

// InsertBlocks mocks base method.
func (m *MockClickhouseRepository) InsertBlocks(ctx context.Context, blocks []model.Block) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBlocks", ctx, blocks)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBlocks indicates an expected call of InsertBlocks.
func (mr *MockClickhouseRepositoryMockRecorder) InsertBlocks(ctx, blocks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBlocks", reflect.TypeOf((*MockClickhouseRepository)(nil).InsertBlocks), ctx, blocks)
}

// InsertTransactionInputs mocks base method.
func (m *MockClickhouseRepository) InsertTransactionInputs(ctx context.Context, inputs []model.TransactionInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransactionInputs", ctx, inputs)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTransactionInputs indicates an expected call of InsertTransactionInputs.
func (mr *MockClickhouseRepositoryMockRecorder) InsertTransactionInputs(ctx, inputs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransactionInputs", reflect.TypeOf((*MockClickhouseRepository)(nil).InsertTransactionInputs), ctx, inputs)
}

// InsertTransactionOutputs mocks base method.
func (m *MockClickhouseRepository) InsertTransactionOutputs(ctx context.Context, outputs []model.TransactionOutput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransactionOutputs", ctx, outputs)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTransactionOutputs indicates an expected call of InsertTransactionOutputs.
func (mr *MockClickhouseRepositoryMockRecorder) InsertTransactionOutputs(ctx, outputs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransactionOutputs", reflect.TypeOf((*MockClickhouseRepository)(nil).InsertTransactionOutputs), ctx, outputs)
}

// InsertTransactions mocks base method.
func (m *MockClickhouseRepository) InsertTransactions(ctx context.Context, txs []model.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransactions", ctx, txs)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTransactions indicates an expected call of InsertTransactions.
func (mr *MockClickhouseRepositoryMockRecorder) InsertTransactions(ctx, txs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransactions", reflect.TypeOf((*MockClickhouseRepository)(nil).InsertTransactions), ctx, txs)
}

// MaxContiguousBlockHeight mocks base method.
func (m *MockClickhouseRepository) MaxContiguousBlockHeight(ctx context.Context, coin model.Coin, network model.Network) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxContiguousBlockHeight", ctx, coin, network)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MaxContiguousBlockHeight indicates an expected call of MaxContiguousBlockHeight.
func (mr *MockClickhouseRepositoryMockRecorder) MaxContiguousBlockHeight(ctx, coin, network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxContiguousBlockHeight", reflect.TypeOf((*MockClickhouseRepository)(nil).MaxContiguousBlockHeight), ctx, coin, network)
}

// RandomMissingBlockHeights mocks base method.
func (m *MockClickhouseRepository) RandomMissingBlockHeights(ctx context.Context, coin model.Coin, network model.Network, maxHeight, limit uint64) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RandomMissingBlockHeights", ctx, coin, network, maxHeight, limit)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RandomMissingBlockHeights indicates an expected call of RandomMissingBlockHeights.
func (mr *MockClickhouseRepositoryMockRecorder) RandomMissingBlockHeights(ctx, coin, network, maxHeight, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RandomMissingBlockHeights", reflect.TypeOf((*MockClickhouseRepository)(nil).RandomMissingBlockHeights), ctx, coin, network, maxHeight, limit)
}

// RandomUnprocessedBlockHeights mocks base method.
func (m *MockClickhouseRepository) RandomUnprocessedBlockHeights(ctx context.Context, coin model.Coin, network model.Network, maxHeight, limit uint64) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RandomUnprocessedBlockHeights", ctx, coin, network, maxHeight, limit)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RandomUnprocessedBlockHeights indicates an expected call of RandomUnprocessedBlockHeights.
func (mr *MockClickhouseRepositoryMockRecorder) RandomUnprocessedBlockHeights(ctx, coin, network, maxHeight, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RandomUnprocessedBlockHeights", reflect.TypeOf((*MockClickhouseRepository)(nil).RandomUnprocessedBlockHeights), ctx, coin, network, maxHeight, limit)
}
