// Code generated by MockGen. DO NOT EDIT.
// Source: types.go

// Package chain is a generated GoMock package.
package chain

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/goodnatureofminers/blockinsight7000-backend/internal/utxo/model"
)

// MockClickhouseRepository is a mock of ClickhouseRepository interface.
type MockClickhouseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClickhouseRepositoryMockRecorder
}

// MockClickhouseRepositoryMockRecorder is the mock recorder for MockClickhouseRepository.
type MockClickhouseRepositoryMockRecorder struct {
	mock *MockClickhouseRepository
}

// NewMockClickhouseRepository creates a new mock instance.
func NewMockClickhouseRepository(ctrl *gomock.Controller) *MockClickhouseRepository {
	mock := &MockClickhouseRepository{ctrl: ctrl}
	mock.recorder = &MockClickhouseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickhouseRepository) EXPECT() *MockClickhouseRepositoryMockRecorder {
	return m.recorder
}

// TransactionOutputs mocks base method.
func (m *MockClickhouseRepository) TransactionOutputs(ctx context.Context, coin model.Coin, network model.Network, txid string) ([]model.TransactionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionOutputs", ctx, coin, network, txid)
	ret0, _ := ret[0].([]model.TransactionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionOutputs indicates an expected call of TransactionOutputs.
func (mr *MockClickhouseRepositoryMockRecorder) TransactionOutputs(ctx, coin, network, txid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionOutputs", reflect.TypeOf((*MockClickhouseRepository)(nil).TransactionOutputs), ctx, coin, network, txid)
}

// TransactionOutputsByTxIDs mocks base method.
func (m *MockClickhouseRepository) TransactionOutputsByTxIDs(ctx context.Context, coin model.Coin, network model.Network, txids []string) (map[string][]model.TransactionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionOutputsByTxIDs", ctx, coin, network, txids)
	ret0, _ := ret[0].(map[string][]model.TransactionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionOutputsByTxIDs indicates an expected call of TransactionOutputsByTxIDs.
func (mr *MockClickhouseRepositoryMockRecorder) TransactionOutputsByTxIDs(ctx, coin, network, txids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionOutputsByTxIDs", reflect.TypeOf((*MockClickhouseRepository)(nil).TransactionOutputsByTxIDs), ctx, coin, network, txids)
}
