// Code generated by MockGen. DO NOT EDIT.
// Source: types.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	btcjson "github.com/btcsuite/btcd/btcjson"
	chainhash "github.com/btcsuite/btcd/chaincfg/chainhash"
	gomock "github.com/golang/mock/gomock"
	model "github.com/goodnatureofminers/blockinsight7000-backend/internal/model"
)

// MockBTCRepository is a mock of BTCRepository interface.
type MockBTCRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBTCRepositoryMockRecorder
}

// MockBTCRepositoryMockRecorder is the mock recorder for MockBTCRepository.
type MockBTCRepositoryMockRecorder struct {
	mock *MockBTCRepository
}

// NewMockBTCRepository creates a new mock instance.
func NewMockBTCRepository(ctrl *gomock.Controller) *MockBTCRepository {
	mock := &MockBTCRepository{ctrl: ctrl}
	mock.recorder = &MockBTCRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBTCRepository) EXPECT() *MockBTCRepositoryMockRecorder {
	return m.recorder
}

// InsertBlocks mocks base method.
func (m *MockBTCRepository) InsertBlocks(ctx context.Context, blocks []model.BTCBlock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBlocks", ctx, blocks)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBlocks indicates an expected call of InsertBlocks.
func (mr *MockBTCRepositoryMockRecorder) InsertBlocks(ctx, blocks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBlocks", reflect.TypeOf((*MockBTCRepository)(nil).InsertBlocks), ctx, blocks)
}

// InsertTransactionInputs mocks base method.
func (m *MockBTCRepository) InsertTransactionInputs(ctx context.Context, inputs []model.BTCTransactionInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransactionInputs", ctx, inputs)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTransactionInputs indicates an expected call of InsertTransactionInputs.
func (mr *MockBTCRepositoryMockRecorder) InsertTransactionInputs(ctx, inputs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransactionInputs", reflect.TypeOf((*MockBTCRepository)(nil).InsertTransactionInputs), ctx, inputs)
}

// InsertTransactionOutputs mocks base method.
func (m *MockBTCRepository) InsertTransactionOutputs(ctx context.Context, outputs []model.BTCTransactionOutput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransactionOutputs", ctx, outputs)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTransactionOutputs indicates an expected call of InsertTransactionOutputs.
func (mr *MockBTCRepositoryMockRecorder) InsertTransactionOutputs(ctx, outputs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransactionOutputs", reflect.TypeOf((*MockBTCRepository)(nil).InsertTransactionOutputs), ctx, outputs)
}

// InsertTransactions mocks base method.
func (m *MockBTCRepository) InsertTransactions(ctx context.Context, txs []model.BTCTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransactions", ctx, txs)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTransactions indicates an expected call of InsertTransactions.
func (mr *MockBTCRepositoryMockRecorder) InsertTransactions(ctx, txs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransactions", reflect.TypeOf((*MockBTCRepository)(nil).InsertTransactions), ctx, txs)
}

// MaxBlockHeight mocks base method.
func (m *MockBTCRepository) MaxBlockHeight(ctx context.Context, network string) (uint64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxBlockHeight", ctx, network)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MaxBlockHeight indicates an expected call of MaxBlockHeight.
func (mr *MockBTCRepositoryMockRecorder) MaxBlockHeight(ctx, network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxBlockHeight", reflect.TypeOf((*MockBTCRepository)(nil).MaxBlockHeight), ctx, network)
}

// RandomMissingBlockHeights mocks base method.
func (m *MockBTCRepository) RandomMissingBlockHeights(ctx context.Context, network string, maxHeight, limit uint64) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RandomMissingBlockHeights", ctx, network, maxHeight, limit)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RandomMissingBlockHeights indicates an expected call of RandomMissingBlockHeights.
func (mr *MockBTCRepositoryMockRecorder) RandomMissingBlockHeights(ctx, network, maxHeight, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RandomMissingBlockHeights", reflect.TypeOf((*MockBTCRepository)(nil).RandomMissingBlockHeights), ctx, network, maxHeight, limit)
}

// TransactionOutputs mocks base method.
func (m *MockBTCRepository) TransactionOutputs(ctx context.Context, network, txid string) ([]model.BTCTransactionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionOutputs", ctx, network, txid)
	ret0, _ := ret[0].([]model.BTCTransactionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionOutputs indicates an expected call of TransactionOutputs.
func (mr *MockBTCRepositoryMockRecorder) TransactionOutputs(ctx, network, txid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionOutputs", reflect.TypeOf((*MockBTCRepository)(nil).TransactionOutputs), ctx, network, txid)
}

// MockBTCRpcClient is a mock of BTCRpcClient interface.
type MockBTCRpcClient struct {
	ctrl     *gomock.Controller
	recorder *MockBTCRpcClientMockRecorder
}

// MockBTCRpcClientMockRecorder is the mock recorder for MockBTCRpcClient.
type MockBTCRpcClientMockRecorder struct {
	mock *MockBTCRpcClient
}

// NewMockBTCRpcClient creates a new mock instance.
func NewMockBTCRpcClient(ctrl *gomock.Controller) *MockBTCRpcClient {
	mock := &MockBTCRpcClient{ctrl: ctrl}
	mock.recorder = &MockBTCRpcClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBTCRpcClient) EXPECT() *MockBTCRpcClientMockRecorder {
	return m.recorder
}

// GetBlockCount mocks base method.
func (m *MockBTCRpcClient) GetBlockCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockCount indicates an expected call of GetBlockCount.
func (mr *MockBTCRpcClientMockRecorder) GetBlockCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockCount", reflect.TypeOf((*MockBTCRpcClient)(nil).GetBlockCount))
}

// GetBlockHash mocks base method.
func (m *MockBTCRpcClient) GetBlockHash(blockHeight int64) (*chainhash.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockHash", blockHeight)
	ret0, _ := ret[0].(*chainhash.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockHash indicates an expected call of GetBlockHash.
func (mr *MockBTCRpcClientMockRecorder) GetBlockHash(blockHeight interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockHash", reflect.TypeOf((*MockBTCRpcClient)(nil).GetBlockHash), blockHeight)
}

// GetBlockVerboseTx mocks base method.
func (m *MockBTCRpcClient) GetBlockVerboseTx(blockHash *chainhash.Hash) (*btcjson.GetBlockVerboseTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockVerboseTx", blockHash)
	ret0, _ := ret[0].(*btcjson.GetBlockVerboseTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockVerboseTx indicates an expected call of GetBlockVerboseTx.
func (mr *MockBTCRpcClientMockRecorder) GetBlockVerboseTx(blockHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockVerboseTx", reflect.TypeOf((*MockBTCRpcClient)(nil).GetBlockVerboseTx), blockHash)
}
