// Code generated by MockGen. DO NOT EDIT.
// Source: types.go

// Package history_ingestor is a generated GoMock package.
package history_ingestor

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	chain "github.com/goodnatureofminers/blockinsight7000-backend/internal/utxo/chain"
	model "github.com/goodnatureofminers/blockinsight7000-backend/internal/utxo/model"
)

// MockHeightFetcher is a mock of HeightFetcher interface.
type MockHeightFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockHeightFetcherMockRecorder
}

// MockHeightFetcherMockRecorder is the mock recorder for MockHeightFetcher.
type MockHeightFetcherMockRecorder struct {
	mock *MockHeightFetcher
}

// NewMockHeightFetcher creates a new mock instance.
func NewMockHeightFetcher(ctrl *gomock.Controller) *MockHeightFetcher {
	mock := &MockHeightFetcher{ctrl: ctrl}
	mock.recorder = &MockHeightFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHeightFetcher) EXPECT() *MockHeightFetcherMockRecorder {
	return m.recorder
}

// FetchMissing mocks base method.
func (m *MockHeightFetcher) FetchMissing(ctx context.Context) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMissing", ctx)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchMissing indicates an expected call of FetchMissing.
func (mr *MockHeightFetcherMockRecorder) FetchMissing(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMissing", reflect.TypeOf((*MockHeightFetcher)(nil).FetchMissing), ctx)
}

// MockBlockProcessor is a mock of BlockProcessor interface.
type MockBlockProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockBlockProcessorMockRecorder
}

// MockBlockProcessorMockRecorder is the mock recorder for MockBlockProcessor.
type MockBlockProcessorMockRecorder struct {
	mock *MockBlockProcessor
}

// NewMockBlockProcessor creates a new mock instance.
func NewMockBlockProcessor(ctrl *gomock.Controller) *MockBlockProcessor {
	mock := &MockBlockProcessor{ctrl: ctrl}
	mock.recorder = &MockBlockProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockProcessor) EXPECT() *MockBlockProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockBlockProcessor) Process(ctx context.Context, heights []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, heights)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockBlockProcessorMockRecorder) Process(ctx, heights interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockBlockProcessor)(nil).Process), ctx, heights)
}

// SetCancelBatcher mocks base method.
func (m *MockBlockProcessor) SetCancelBatcher(cancel func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCancelBatcher", cancel)
}

// SetCancelBatcher indicates an expected call of SetCancelBatcher.
func (mr *MockBlockProcessorMockRecorder) SetCancelBatcher(cancel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCancelBatcher", reflect.TypeOf((*MockBlockProcessor)(nil).SetCancelBatcher), cancel)
}

// MockBlockWriter is a mock of BlockWriter interface.
type MockBlockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockBlockWriterMockRecorder
}

// MockBlockWriterMockRecorder is the mock recorder for MockBlockWriter.
type MockBlockWriterMockRecorder struct {
	mock *MockBlockWriter
}

// NewMockBlockWriter creates a new mock instance.
func NewMockBlockWriter(ctrl *gomock.Controller) *MockBlockWriter {
	mock := &MockBlockWriter{ctrl: ctrl}
	mock.recorder = &MockBlockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockWriter) EXPECT() *MockBlockWriterMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockBlockWriter) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockBlockWriterMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockBlockWriter)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockBlockWriter) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockBlockWriterMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockBlockWriter)(nil).Stop))
}

// WriteBlock mocks base method.
func (m *MockBlockWriter) WriteBlock(ctx context.Context, b model.InsertBlock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBlock", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteBlock indicates an expected call of WriteBlock.
func (mr *MockBlockWriterMockRecorder) WriteBlock(ctx, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBlock", reflect.TypeOf((*MockBlockWriter)(nil).WriteBlock), ctx, b)
}

// MockHistoryIngesterMetrics is a mock of HistoryIngesterMetrics interface.
type MockHistoryIngesterMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryIngesterMetricsMockRecorder
}

// MockHistoryIngesterMetricsMockRecorder is the mock recorder for MockHistoryIngesterMetrics.
type MockHistoryIngesterMetricsMockRecorder struct {
	mock *MockHistoryIngesterMetrics
}

// NewMockHistoryIngesterMetrics creates a new mock instance.
func NewMockHistoryIngesterMetrics(ctrl *gomock.Controller) *MockHistoryIngesterMetrics {
	mock := &MockHistoryIngesterMetrics{ctrl: ctrl}
	mock.recorder = &MockHistoryIngesterMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryIngesterMetrics) EXPECT() *MockHistoryIngesterMetricsMockRecorder {
	return m.recorder
}

// ObserveFetchMissing mocks base method.
func (m *MockHistoryIngesterMetrics) ObserveFetchMissing(err error, started time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveFetchMissing", err, started)
}

// ObserveFetchMissing indicates an expected call of ObserveFetchMissing.
func (mr *MockHistoryIngesterMetricsMockRecorder) ObserveFetchMissing(err, started interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveFetchMissing", reflect.TypeOf((*MockHistoryIngesterMetrics)(nil).ObserveFetchMissing), err, started)
}

// ObserveProcessBatch mocks base method.
func (m *MockHistoryIngesterMetrics) ObserveProcessBatch(err error, heights int, started time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveProcessBatch", err, heights, started)
}

// ObserveProcessBatch indicates an expected call of ObserveProcessBatch.
func (mr *MockHistoryIngesterMetricsMockRecorder) ObserveProcessBatch(err, heights, started interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveProcessBatch", reflect.TypeOf((*MockHistoryIngesterMetrics)(nil).ObserveProcessBatch), err, heights, started)
}

// ObserveProcessHeight mocks base method.
func (m *MockHistoryIngesterMetrics) ObserveProcessHeight(err error, height uint64, started time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveProcessHeight", err, height, started)
}

// ObserveProcessHeight indicates an expected call of ObserveProcessHeight.
func (mr *MockHistoryIngesterMetricsMockRecorder) ObserveProcessHeight(err, height, started interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveProcessHeight", reflect.TypeOf((*MockHistoryIngesterMetrics)(nil).ObserveProcessHeight), err, height, started)
}

// MockHistorySource is a mock of HistorySource interface.
type MockHistorySource struct {
	ctrl     *gomock.Controller
	recorder *MockHistorySourceMockRecorder
}

// MockHistorySourceMockRecorder is the mock recorder for MockHistorySource.
type MockHistorySourceMockRecorder struct {
	mock *MockHistorySource
}

// NewMockHistorySource creates a new mock instance.
func NewMockHistorySource(ctrl *gomock.Controller) *MockHistorySource {
	mock := &MockHistorySource{ctrl: ctrl}
	mock.recorder = &MockHistorySourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistorySource) EXPECT() *MockHistorySourceMockRecorder {
	return m.recorder
}

// FetchBlock mocks base method.
func (m *MockHistorySource) FetchBlock(ctx context.Context, height uint64) (*chain.HistoryBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchBlock", ctx, height)
	ret0, _ := ret[0].(*chain.HistoryBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchBlock indicates an expected call of FetchBlock.
func (mr *MockHistorySourceMockRecorder) FetchBlock(ctx, height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchBlock", reflect.TypeOf((*MockHistorySource)(nil).FetchBlock), ctx, height)
}

// LatestHeight mocks base method.
func (m *MockHistorySource) LatestHeight(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestHeight", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestHeight indicates an expected call of LatestHeight.
func (mr *MockHistorySourceMockRecorder) LatestHeight(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestHeight", reflect.TypeOf((*MockHistorySource)(nil).LatestHeight), ctx)
}

// MockClickhouseRepository is a mock of ClickhouseRepository interface.
type MockClickhouseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClickhouseRepositoryMockRecorder
}

// MockClickhouseRepositoryMockRecorder is the mock recorder for MockClickhouseRepository.
type MockClickhouseRepositoryMockRecorder struct {
	mock *MockClickhouseRepository
}

// NewMockClickhouseRepository creates a new mock instance.
func NewMockClickhouseRepository(ctrl *gomock.Controller) *MockClickhouseRepository {
	mock := &MockClickhouseRepository{ctrl: ctrl}
	mock.recorder = &MockClickhouseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickhouseRepository) EXPECT() *MockClickhouseRepositoryMockRecorder {
	return m.recorder
}

// InsertBlocks mocks base method.
func (m *MockClickhouseRepository) InsertBlocks(ctx context.Context, blocks []model.Block) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBlocks", ctx, blocks)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBlocks indicates an expected call of InsertBlocks.
func (mr *MockClickhouseRepositoryMockRecorder) InsertBlocks(ctx, blocks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBlocks", reflect.TypeOf((*MockClickhouseRepository)(nil).InsertBlocks), ctx, blocks)
}

// InsertTransactionOutputs mocks base method.
func (m *MockClickhouseRepository) InsertTransactionOutputs(ctx context.Context, outputs []model.TransactionOutput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransactionOutputs", ctx, outputs)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTransactionOutputs indicates an expected call of InsertTransactionOutputs.
func (mr *MockClickhouseRepositoryMockRecorder) InsertTransactionOutputs(ctx, outputs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransactionOutputs", reflect.TypeOf((*MockClickhouseRepository)(nil).InsertTransactionOutputs), ctx, outputs)
}

// InsertTransactions mocks base method.
func (m *MockClickhouseRepository) InsertTransactions(ctx context.Context, txs []model.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransactions", ctx, txs)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTransactions indicates an expected call of InsertTransactions.
func (mr *MockClickhouseRepositoryMockRecorder) InsertTransactions(ctx, txs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransactions", reflect.TypeOf((*MockClickhouseRepository)(nil).InsertTransactions), ctx, txs)
}

// RandomMissingBlockHeights mocks base method.
func (m *MockClickhouseRepository) RandomMissingBlockHeights(ctx context.Context, coin model.Coin, network model.Network, maxHeight, limit uint64) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RandomMissingBlockHeights", ctx, coin, network, maxHeight, limit)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RandomMissingBlockHeights indicates an expected call of RandomMissingBlockHeights.
func (mr *MockClickhouseRepositoryMockRecorder) RandomMissingBlockHeights(ctx, coin, network, maxHeight, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RandomMissingBlockHeights", reflect.TypeOf((*MockClickhouseRepository)(nil).RandomMissingBlockHeights), ctx, coin, network, maxHeight, limit)
}
