// Code generated by MockGen. DO NOT EDIT.
// Source: types.go

// Package bitcoin is a generated GoMock package.
package bitcoin

import (
	context "context"
	reflect "reflect"
	time "time"

	btcjson "github.com/btcsuite/btcd/btcjson"
	chainhash "github.com/btcsuite/btcd/chaincfg/chainhash"
	gomock "github.com/golang/mock/gomock"
	model "github.com/goodnatureofminers/blockinsight7000-backend/internal/utxo/model"
)

// MockTransactionOutputResolver is a mock of TransactionOutputResolver interface.
type MockTransactionOutputResolver struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionOutputResolverMockRecorder
}

// MockTransactionOutputResolverMockRecorder is the mock recorder for MockTransactionOutputResolver.
type MockTransactionOutputResolverMockRecorder struct {
	mock *MockTransactionOutputResolver
}

// NewMockTransactionOutputResolver creates a new mock instance.
func NewMockTransactionOutputResolver(ctrl *gomock.Controller) *MockTransactionOutputResolver {
	mock := &MockTransactionOutputResolver{ctrl: ctrl}
	mock.recorder = &MockTransactionOutputResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionOutputResolver) EXPECT() *MockTransactionOutputResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockTransactionOutputResolver) Resolve(ctx context.Context, txid string) ([]model.TransactionOutputLookup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, txid)
	ret0, _ := ret[0].([]model.TransactionOutputLookup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockTransactionOutputResolverMockRecorder) Resolve(ctx, txid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockTransactionOutputResolver)(nil).Resolve), ctx, txid)
}

// ResolveBatch mocks base method.
func (m *MockTransactionOutputResolver) ResolveBatch(ctx context.Context, txids []string) (map[string][]model.TransactionOutputLookup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveBatch", ctx, txids)
	ret0, _ := ret[0].(map[string][]model.TransactionOutputLookup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveBatch indicates an expected call of ResolveBatch.
func (mr *MockTransactionOutputResolverMockRecorder) ResolveBatch(ctx, txids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveBatch", reflect.TypeOf((*MockTransactionOutputResolver)(nil).ResolveBatch), ctx, txids)
}

// MockRPCMetrics is a mock of RPCMetrics interface.
type MockRPCMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockRPCMetricsMockRecorder
}

// MockRPCMetricsMockRecorder is the mock recorder for MockRPCMetrics.
type MockRPCMetricsMockRecorder struct {
	mock *MockRPCMetrics
}

// NewMockRPCMetrics creates a new mock instance.
func NewMockRPCMetrics(ctrl *gomock.Controller) *MockRPCMetrics {
	mock := &MockRPCMetrics{ctrl: ctrl}
	mock.recorder = &MockRPCMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCMetrics) EXPECT() *MockRPCMetricsMockRecorder {
	return m.recorder
}

// Observe mocks base method.
func (m *MockRPCMetrics) Observe(operation string, err error, started time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Observe", operation, err, started)
}

// Observe indicates an expected call of Observe.
func (mr *MockRPCMetricsMockRecorder) Observe(operation, err, started interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Observe", reflect.TypeOf((*MockRPCMetrics)(nil).Observe), operation, err, started)
}

// MockRPCClient is a mock of RPCClient interface.
type MockRPCClient struct {
	ctrl     *gomock.Controller
	recorder *MockRPCClientMockRecorder
}

// MockRPCClientMockRecorder is the mock recorder for MockRPCClient.
type MockRPCClientMockRecorder struct {
	mock *MockRPCClient
}

// NewMockRPCClient creates a new mock instance.
func NewMockRPCClient(ctrl *gomock.Controller) *MockRPCClient {
	mock := &MockRPCClient{ctrl: ctrl}
	mock.recorder = &MockRPCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCClient) EXPECT() *MockRPCClientMockRecorder {
	return m.recorder
}

// GetBlockCount mocks base method.
func (m *MockRPCClient) GetBlockCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockCount indicates an expected call of GetBlockCount.
func (mr *MockRPCClientMockRecorder) GetBlockCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockCount", reflect.TypeOf((*MockRPCClient)(nil).GetBlockCount))
}

// GetBlockHash mocks base method.
func (m *MockRPCClient) GetBlockHash(blockHeight int64) (*chainhash.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockHash", blockHeight)
	ret0, _ := ret[0].(*chainhash.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockHash indicates an expected call of GetBlockHash.
func (mr *MockRPCClientMockRecorder) GetBlockHash(blockHeight interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockHash", reflect.TypeOf((*MockRPCClient)(nil).GetBlockHash), blockHeight)
}

// GetBlockVerboseTx mocks base method.
func (m *MockRPCClient) GetBlockVerboseTx(blockHash *chainhash.Hash) (*btcjson.GetBlockVerboseTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockVerboseTx", blockHash)
	ret0, _ := ret[0].(*btcjson.GetBlockVerboseTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockVerboseTx indicates an expected call of GetBlockVerboseTx.
func (mr *MockRPCClientMockRecorder) GetBlockVerboseTx(blockHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockVerboseTx", reflect.TypeOf((*MockRPCClient)(nil).GetBlockVerboseTx), blockHash)
}

// MockScriptDecoder is a mock of ScriptDecoder interface.
type MockScriptDecoder struct {
	ctrl     *gomock.Controller
	recorder *MockScriptDecoderMockRecorder
}

// MockScriptDecoderMockRecorder is the mock recorder for MockScriptDecoder.
type MockScriptDecoderMockRecorder struct {
	mock *MockScriptDecoder
}

// NewMockScriptDecoder creates a new mock instance.
func NewMockScriptDecoder(ctrl *gomock.Controller) *MockScriptDecoder {
	mock := &MockScriptDecoder{ctrl: ctrl}
	mock.recorder = &MockScriptDecoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScriptDecoder) EXPECT() *MockScriptDecoderMockRecorder {
	return m.recorder
}

// decodeAddresses mocks base method.
func (m *MockScriptDecoder) decodeAddresses(vout btcjson.Vout) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "decodeAddresses", vout)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// decodeAddresses indicates an expected call of decodeAddresses.
func (mr *MockScriptDecoderMockRecorder) decodeAddresses(vout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "decodeAddresses", reflect.TypeOf((*MockScriptDecoder)(nil).decodeAddresses), vout)
}

// MockOutputConverter is a mock of OutputConverter interface.
type MockOutputConverter struct {
	ctrl     *gomock.Controller
	recorder *MockOutputConverterMockRecorder
}

// MockOutputConverterMockRecorder is the mock recorder for MockOutputConverter.
type MockOutputConverterMockRecorder struct {
	mock *MockOutputConverter
}

// NewMockOutputConverter creates a new mock instance.
func NewMockOutputConverter(ctrl *gomock.Controller) *MockOutputConverter {
	mock := &MockOutputConverter{ctrl: ctrl}
	mock.recorder = &MockOutputConverterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutputConverter) EXPECT() *MockOutputConverterMockRecorder {
	return m.recorder
}

// Convert mocks base method.
func (m *MockOutputConverter) Convert(tx btcjson.TxRawResult, blockHeight uint64) ([]model.TransactionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Convert", tx, blockHeight)
	ret0, _ := ret[0].([]model.TransactionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Convert indicates an expected call of Convert.
func (mr *MockOutputConverterMockRecorder) Convert(tx, blockHeight interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Convert", reflect.TypeOf((*MockOutputConverter)(nil).Convert), tx, blockHeight)
}

// ConvertLookup mocks base method.
func (m *MockOutputConverter) ConvertLookup(tx btcjson.TxRawResult) ([]model.TransactionOutputLookup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertLookup", tx)
	ret0, _ := ret[0].([]model.TransactionOutputLookup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConvertLookup indicates an expected call of ConvertLookup.
func (mr *MockOutputConverterMockRecorder) ConvertLookup(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertLookup", reflect.TypeOf((*MockOutputConverter)(nil).ConvertLookup), tx)
}
